APP_VERSION = "V1.1.0"

FRAME_MAX_HDR_SIZE = 4
FRAME_MAX_CRC_SIZE = 2
FRAME_MAX_PAYLOAD_SIZE = 255 - FRAME_MAX_HDR_SIZE - FRAME_MAX_CRC_SIZE
FRAME_MAX_CMD_SIZE = FRAME_MAX_PAYLOAD_SIZE + FRAME_MAX_HDR_SIZE + FRAME_MAX_CRC_SIZE

SENS_MAX_POINTS = 32

# COMMANDS
SENS_ITF_VER_CMD          = 0x00
SENS_IDENT_CMD            = 0x01
SENS_POINT_DESC_BASE_CMD  = 0x10
SENS_POINT_READ_BASE_CMD  = 0x30
SENS_POINT_WRITE_BASE_CMD = 0x50
NO_CMD                    = 0xFF

# POINT TYPES
POINT_TYPE_UINT8  = 0
POINT_TYPE_INT8   = 1
POINT_TYPE_UINT16 = 2
POINT_TYPE_INT16  = 3
POINT_TYPE_UINT32 = 4
POINT_TYPE_INT32  = 5
POINT_TYPE_UINT64 = 6
POINT_TYPE_INT64  = 7
POINT_TYPE_FLOAT  = 8
POINT_TYPE_DOUBLE = 9
POINT_TYPE_ARRAY  = 10

POINT_RO = 0
POINT_WO = 1
POINT_RW = 2
POINT_RIGHTS = ['RO','WO','RW']

# SERIAL
SERIAL_TIMEOUT = 1
SERIAL_MASTER = "COM9"
#SERIAL_MASTER = '/dev/ttyUSB0'
#SERIAL_MASTER = '/dev/ttyACM0'
#SERIAL_DEVICE = '/dev/ttyUSB1'
#SERIAL_BAUD = 115200
SERIAL_BAUD = 9600

EMULATION = False
PIPE_TX = '/tmp/pipe_tx'
PIPE_RX = '/tmp/pipe_rx'

ENABLE_WIRESHARK = False
PIPE_WIRESHAK = '/tmp/pipe_wireshark'
